apiVersion: skaffold/v2beta6
kind: Config
deploy:
  kubectl:
    manifests:
      - './k8s/*'
build:
  local:
    push: false
  artifacts:
    - image: souravdeveloper/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*ts
            dest: .
    - image: souravdeveloper/followers
      context: followers
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*ts
            dest: .
    - image: souravdeveloper/post
      context: post
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*ts
            dest: .
