apiVersion: apps/v1
kind: Deployment
metadata:
  name: followers-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: followers
  template:
    metadata:
      labels:
        app: followers
    spec:
      containers:
        - name: followers
          image: souravdeveloper/followers
          env:
            - name: DB_URL
              value: mongodb+srv://Sourav:<password>@cluster0.nw0ur.mongodb.net/followers?retryWrites=true&w=majorityw=majority

            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: NATS_URL
              value: 'http://nats-srv:4222'

            - name: NATS_CLUSTER
              value: instagram

            - name: JWT_EXP
              value: '90d'

            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: db-user
                  key: USER_NAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: DB_PASSWORD

            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: followers-srv
spec:
  selector:
    app: followers
  ports:
    - name: followers
      protocol: TCP
      port: 3000
      targetPort: 3000
